import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'text-on-tertiary-container',
    'text-secondary',
    'text-on-surface',
    'text-on-surface-variant',
    'bg-on-tertiary-container',
    'bg-secondary',
    'bg-on-surface',
    'bg-on-tertiary-container/10',
    'bg-secondary/10',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#009669",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "surface": "#f8f9ff",
        "outline": "#76777d",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#7bd0ff",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#004d6a",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "inverse-surface": "#213145",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "primary-container": "#131b2e",
        "tertiary-fixed-dim": "#45dfa4",
        "on-secondary-fixed": "#001e2c",
        "primary-fixed": "#dae2fd",
        "surface-tint": "#565e74",
        "secondary-fixed": "#c4e7ff",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "secondary-container": "#40c2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#002114",
        "on-background": "#0b1c30",
        "on-tertiary-fixed-variant": "#005137",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#68fcbf",
        "on-primary-container": "#7c839b",
        "tertiary-container": "#002114",
        "on-primary-fixed": "#131b2e",
        "tertiary": "#000000",
        "secondary": "#00668a",
        "on-secondary-fixed-variant": "#004c69",
        "surface-container-low": "#eff4ff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "3xl": "1.5rem",
        "2xl": "1rem",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "0.75rem",
        "margin-tablet": "1.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "margin": "3rem",
        "space-xl": "2.5rem",
        "space-2xl": "3rem",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        metric: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.035em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-xs": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "metric-display": ["64px", { lineHeight: "64px", letterSpacing: "-0.04em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
