'use client';

import { useState } from 'react';
import Footer from '@/components/shared/Footer';
import AIAssistant from '@/components/shared/AIAssistant';
import { NEIGHBORHOOD_METRICS, FORECAST } from '@/lib/constants';

export default function WeatherPage() {
  const [selectedIdx, setSelectedIdx] = useState(0);

  return (
    <main className="w-full pt-16 flex-grow flex flex-col">
      <section className="w-full px-gutter md:px-margin py-space-lg flex flex-col gap-space-lg max-w-[1360px] mx-auto">
        <section className="relative w-full rounded-2xl bg-surface-container-lowest shadow-md overflow-hidden p-space-lg md:p-space-xl">
          <div className="absolute -top-32 -right-24 w-96 h-96 rounded-full bg-secondary-fixed opacity-40 blur-3xl pointer-events-none"></div>
          <div className="absolute -bottom-24 -left-20 w-80 h-80 rounded-full bg-tertiary-fixed opacity-30 blur-3xl pointer-events-none"></div>
          <div className="relative z-10 flex flex-col lg:flex-row lg:items-end justify-between gap-space-lg">
            <div className="flex flex-col gap-space-sm max-w-2xl">
              <div className="flex items-center gap-space-xs"><span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-surface-container text-on-surface-variant font-label-xs text-label-xs uppercase tracking-wider font-semibold"><span className="w-2 h-2 rounded-full bg-on-tertiary-container animate-pulse"></span> SF Bay Grid • Live Telemetry</span><span className="font-label-xs text-label-xs text-on-surface-variant">Updated every 60s</span></div>
              <h1 className="font-headline-lg text-headline-lg text-on-surface tracking-tight mt-1">Jaipur Weather &amp; Microclimates</h1>
              <p className="font-body-md text-body-md text-on-surface-variant">Hyperlocal atmospheric, UV index, and particulate sensor network streaming real-time environmental metrics across 36 neighborhood nodes.</p>
              <div className="flex flex-wrap items-center gap-y-2 gap-x-4 mt-space-sm pt-space-xs">
                {[
                  { icon: 'thermostat', text: 'High 71° / Low 54°' },
                  { icon: 'water_drop', text: 'Humidity 62%' },
                  { icon: 'air', text: 'Wind 9 mph WSW' },
                  { icon: 'wb_sunny', text: 'UV 5 Moderate' },
                ].map((m) => <div key={m.text} className="flex items-center gap-1 text-on-surface-variant font-body-sm text-body-sm"><span className="material-symbols-outlined text-[18px] text-secondary">{m.icon}</span><span>{m.text}</span></div>)}
              </div>
            </div>
            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-space-lg bg-surface-container-low/80 backdrop-blur-md rounded-xl p-space-md shadow-sm">
              <div className="flex items-baseline gap-2"><span className="font-metric-display text-metric-display text-on-surface tracking-tighter">68°</span><div className="flex flex-col"><span className="font-headline-sm text-headline-sm text-on-surface">Partly Cloudy</span><span className="font-body-sm text-body-sm text-on-surface-variant">C-Scheme &amp; Inner Bay</span></div></div>
              <div className="h-12 w-px bg-outline-variant/40 hidden sm:block"></div>
              <div className="flex items-center gap-space-sm"><div className="relative w-12 h-12 flex items-center justify-center"><svg className="w-12 h-12 -rotate-90" viewBox="0 0 48 48"><circle className="stroke-surface-container-high" cx="24" cy="24" fill="none" r="20" strokeWidth="4"></circle><circle className="stroke-tertiary-fixed-dim" cx="24" cy="24" fill="none" r="20" strokeDasharray="125.6" strokeDashoffset="30" strokeLinecap="round" strokeWidth="4"></circle></svg><span className="material-symbols-outlined absolute text-[20px] text-on-tertiary-container">eco</span></div><div className="flex flex-col"><span className="font-label-xs text-label-xs uppercase tracking-wider text-on-tertiary-container font-semibold">AQI 24 • Pristine</span><span className="font-body-sm text-body-sm text-on-surface-variant">Ideal for all outdoor activities</span></div></div>
            </div>
          </div>
        </section>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-space-md">
          {[
            { label: 'Pacific Inflow', title: 'Marine Layer Cleared at 10:15 AM', gradient: 'from-primary/80 via-primary/20 to-transparent' },
            { label: 'Solar Exposure', title: 'Peak Solar Irradiance: 840 W/m²', gradient: 'from-primary/80 via-primary/20 to-transparent' },
            { label: 'Thermal Gradient', title: '+12°F Variance Across 7 Miles', gradient: 'from-primary/80 via-primary/20 to-transparent' },
          ].map((s, i) => <div key={i} className="relative h-44 rounded-2xl overflow-hidden shadow-sm group"><img className="w-full h-full object-cover transition-transform duration-700 ease-out group-hover:scale-105" src={`https://picsum.photos/seed/sf${i}/400/300`} alt={s.title} /><div className={`absolute inset-0 bg-gradient-to-t ${s.gradient} flex flex-col justify-end p-space-md`}><span className="font-label-xs text-label-xs text-secondary-fixed uppercase tracking-wider font-semibold">{s.label}</span><span className="font-headline-sm text-headline-sm text-on-primary">{s.title}</span></div></div>)}
        </div>
        <section className="w-full rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm">
          <div className="flex items-center justify-between mb-space-md"><div className="flex items-center gap-space-xs"><span className="material-symbols-outlined text-[20px] text-secondary">calendar_today</span><span className="font-headline-sm text-headline-sm text-on-surface">7-Day Civic Atmospheric Outlook</span></div><span className="font-label-xs text-label-xs uppercase text-on-surface-variant tracking-wider font-medium">Regional Inversion Predictive Model</span></div>
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-space-sm pt-space-xs">
            {FORECAST.map((f, i) => <div key={i} className={`flex flex-col items-center justify-between p-space-md rounded-xl transition-all hover:shadow-md cursor-pointer ${i === selectedIdx ? 'bg-surface-container-low shadow-sm' : 'bg-surface hover:bg-surface-container-low'}`} onClick={() => setSelectedIdx(i)}><span className="font-label-md text-label-md font-semibold text-on-surface">{f.day}</span><span className="font-label-xs text-label-xs text-on-surface-variant mt-0.5">{f.date}</span><div className="my-space-md flex flex-col items-center"><span className="material-symbols-outlined text-[32px] text-secondary-container" style={{ fontVariationSettings: { 'FILL': 1 } as any }}>{f.icon}</span><span className="font-label-xs text-label-xs text-on-surface-variant mt-1">{f.precip} Precip</span></div><div className="w-full flex flex-col gap-1 items-center"><div className="flex items-center justify-between w-full text-on-surface font-body-sm text-body-sm font-medium"><span className="text-on-surface-variant">{f.low}°</span><span>{f.high}°</span></div><div className="w-full h-1.5 rounded-full bg-surface-container-high overflow-hidden relative"><div className="absolute left-[20%] right-[10%] h-full rounded-full bg-gradient-to-r from-secondary-fixed-dim to-secondary-container"></div></div></div><span className="font-label-xs text-label-xs text-on-surface-variant mt-2 text-center">{f.condition}</span></div>)}
          </div>
        </section>
        <section className="flex flex-col gap-space-md">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-space-xs"><div><span className="font-label-xs text-label-xs uppercase tracking-wider text-on-surface-variant font-semibold">Localized Grid Array</span><h2 className="font-headline-md text-headline-md text-on-surface">Neighborhood Microclimate Readings</h2></div><span className="font-body-sm text-body-sm text-on-surface-variant">4 Active Sensor Quadrants</span></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-space-md">
            {NEIGHBORHOOD_METRICS.map((n) => <div key={n.id} className="flex flex-col justify-between rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm hover:shadow-md transition-shadow"><div><div className="flex items-center justify-between"><span className="px-2 py-0.5 rounded-full bg-surface-container-low text-on-surface-variant font-label-xs text-label-xs font-semibold">{n.name.split(' ')[0]} Node</span><span className="w-2 h-2 rounded-full bg-tertiary-fixed-dim"></span></div><div className="mt-space-md"><h3 className="font-headline-sm text-headline-sm text-on-surface">{n.name}</h3><div className="flex items-baseline gap-2 mt-1"><span className="font-headline-lg text-headline-lg text-on-surface">{n.temp}°F</span><span className="font-body-sm text-body-sm text-on-surface-variant">Coastal marine gate</span></div></div></div><div className="mt-space-md flex flex-col gap-2"><div className="flex items-center justify-between font-body-sm text-body-sm"><span className="text-on-surface-variant flex items-center gap-1"><span className="material-symbols-outlined text-[16px] text-tertiary-fixed-dim">shield</span> AQI</span><span className="font-semibold text-on-tertiary-container">{n.aqi} ({n.aqiLabel})</span></div><div className="w-full h-1 bg-surface-container rounded-full overflow-hidden"><div className="h-full bg-on-tertiary-container rounded-full" style={{ width: `${n.aqi}%` }}></div></div><div className="flex items-center justify-between font-body-sm text-body-sm pt-1"><span className="text-on-surface-variant flex items-center gap-1"><span className="material-symbols-outlined text-[16px] text-secondary">wb_sunny</span> UV Index</span><span className="font-semibold text-on-surface">{n.uv}</span></div><div className="flex items-center justify-between font-body-sm text-body-sm pt-1"><span className="text-on-surface-variant flex items-center gap-1"><span className="material-symbols-outlined text-[16px] text-secondary">air</span> Wind &amp; Air</span><span className="text-on-surface">{n.wind} • {n.hum}</span></div></div><div className="mt-space-lg pt-space-sm bg-surface-container-low rounded-xl p-2.5 flex items-center gap-2"><span className="material-symbols-outlined text-[18px] text-secondary">info</span><span className="font-body-sm text-body-sm text-on-surface-variant">{n.tip}</span></div></div>)}
          </div>
        </section>
        <section className="w-full rounded-2xl bg-surface-container-lowest p-space-lg shadow-sm">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-space-md pb-space-md"><div><div className="flex items-center gap-space-xs"><span className="w-2.5 h-2.5 rounded-full bg-on-tertiary-container"></span><span className="font-headline-sm text-headline-sm text-on-surface">24-Hour Air Quality Telemetry</span></div><p className="font-body-sm text-body-sm text-on-surface-variant mt-0.5">EPA Standardized Particulate Sensor Grid across all municipal districts (12:00 AM – 11:59 PM).</p></div><div className="flex items-center gap-space-sm px-space-md py-2 rounded-xl bg-surface-container-low"><span className="material-symbols-outlined text-[18px] text-secondary">trending_up</span><span className="font-body-sm text-body-sm text-on-surface font-medium">Peak: <span className="font-semibold">34 AQI</span> at 8:00 AM (Commute influx)</span></div></div>
          <div className="w-full h-56 relative pt-space-sm pb-space-xs"><svg className="w-full h-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 1000 200"><defs><linearGradient id="aqiGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#45dfa4" stopOpacity="0.35"></stop><stop offset="70%" stopColor="#7bd0ff" stopOpacity="0.10"></stop><stop offset="100%" stopColor="#f8f9ff" stopOpacity="0.0"></stop></linearGradient></defs><line stroke="#eff4ff" strokeDasharray="4,4" strokeWidth="1.5" x1="0" x2="1000" y1="40" y2="40"></line><line stroke="#eff4ff" strokeDasharray="4,4" strokeWidth="1.5" x1="0" x2="1000" y1="90" y2="90"></line><line stroke="#eff4ff" strokeDasharray="4,4" strokeWidth="1.5" x1="0" x2="1000" y1="140" y2="140"></line><path d="M 0,150 C 80,155 120,165 200,160 C 280,155 320,110 380,50 C 420,20 460,70 540,85 C 620,100 680,115 760,110 C 840,105 920,135 1000,140 L 1000,200 L 0,200 Z" fill="url(#aqiGradient)"></path><path d="M 0,150 C 80,155 120,165 200,160 C 280,155 320,110 380,50 C 420,20 460,70 540,85 C 620,100 680,115 760,110 C 840,105 920,135 1000,140" fill="none" stroke="#009669" strokeLinecap="round" strokeWidth="2.5"></path><circle cx="380" cy="50" fill="#009669" r="5" stroke="#ffffff" strokeWidth="2.5"></circle><circle cx="1000" cy="140" fill="#009669" r="4.5" stroke="#ffffff" strokeWidth="2"></circle></svg></div>
          <div className="flex items-center justify-between text-on-surface-variant font-label-xs text-label-xs pt-space-xs"><span>12:00 AM (16 AQI)</span><span>4:00 AM (18 AQI)</span><span className="font-semibold text-on-surface">8:00 AM (34 AQI Peak)</span><span>12:00 PM (25 AQI)</span><span>4:00 PM (22 AQI)</span><span>8:00 PM (20 AQI)</span><span className="font-semibold text-on-tertiary-container">Now: 24 AQI</span></div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-space-sm pt-space-lg">
            {[{ label: 'Fine Particulate', value: '5.4', unit: 'μg/m³', status: 'Optimal' },{ label: 'Coarse Dust', value: '12.0', unit: 'μg/m³', status: 'Optimal' },{ label: 'Ground Ozone', value: '0.028', unit: 'ppm', status: 'Minimal' },{ label: 'Nitrogen Dioxide', value: '11.0', unit: 'ppb', status: 'Low' }].map((p) => <div key={p.label} className="p-space-md rounded-xl bg-surface-container-low flex flex-col justify-between"><div className="flex items-center justify-between"><span className="font-label-xs text-label-xs uppercase tracking-wider text-on-surface-variant font-semibold">{p.label}</span><span className="px-1.5 py-0.5 rounded bg-surface-container-lowest text-on-tertiary-container font-label-xs text-label-xs">{p.status}</span></div><div className="mt-2"><span className="font-headline-sm text-headline-sm text-on-surface font-semibold">{p.value}</span><span className="block font-label-xs text-label-xs text-on-surface-variant">{p.unit}</span></div></div>)}
          </div>
        </section>
        <div className="w-full flex flex-col md:flex-row items-center justify-between p-space-md bg-surface-container-low rounded-xl gap-space-md">
          <div className="flex items-center gap-space-md"><div className="w-10 h-10 rounded-full bg-secondary-fixed flex items-center justify-center text-on-secondary-container"><span className="material-symbols-outlined text-[22px]">sensors</span></div><div><span className="font-headline-sm text-headline-sm text-on-surface block">Resident Atmospheric Advisory</span><span className="font-body-sm text-body-sm text-on-surface-variant">Zero active air quality alerts for Jaipur County. Next tidal marine fog cycle expected at 9:30 PM.</span></div></div>
          <div className="flex items-center gap-space-sm w-full md:w-auto justify-end"><button className="px-space-md py-2 rounded bg-surface-container-lowest text-on-surface font-label-md text-label-md shadow-sm hover:bg-surface-container transition-colors" type="button">Download Raw Sensor CSV</button><button className="px-space-md py-2 rounded bg-primary text-on-primary font-label-md text-label-md hover:bg-primary-container transition-colors flex items-center gap-1.5" type="button"><span className="material-symbols-outlined text-[16px]">notifications_active</span> Set AQI Alert Threshold</button></div>
        </div>
      </section>
      <Footer />
      <AIAssistant />
    </main>
  );
}
